version: 0.0
os: linux

files:
  - source: /
    destination: /home/ec2-user

hooks:
  ApplicationStop:
    - location: Script/kill_process.sh # before stop, kill process
  BeforeInstall:
    - location: Script/remove_before.sh # before remove, remove previous files
  ApplicationStart:
    - location: Script/run_process.sh # when start, run process
